// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class QATaskTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void qATask() {
    driver.get("https://qa.putraprima.id/");
    driver.manage().window().setSize(new Dimension(1920, 1050));
    driver.findElement(By.linkText("Terms Of Service")).click();
    driver.findElement(By.linkText("Privacy Policy")).click();
    driver.findElement(By.id("input")).click();
    driver.findElement(By.id("input")).sendKeys("0");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys("170");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys("-1");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys("171");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.id("input")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys("hallo");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys("1.2");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.id("input")).click();
    driver.findElement(By.id("input")).sendKeys("1,2");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys("-10");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys("+10");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.id("input")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys("$");
    driver.findElement(By.id("hitung")).click();
    driver.findElement(By.cssSelector(".d-flex")).click();
    driver.findElement(By.id("input")).sendKeys(" ");
    driver.findElement(By.id("hitung")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".d-flex"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".d-flex"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".d-flex"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".d-flex")).click();
  }
}

